### ISSUE TITLE
Error executing hooks: 'SJ' object has no attribute 'core'

### ISSUE THREAD

**Issue by nordic-style** [Gutz-Pilz/pyLoad-stuff#39]
Mit dem aktuellen stable branch bekomm ich folgende Meldung:

```
28.07.2015 01:34:06 DEBUG     HOOK UpdateManager : LOAD URL http://updatemanager.pyload.org | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | just_header=False | post={} | ref=True
28.07.2015 01:34:06 ERROR     Error executing hooks: 'SJ' object has no attribute 'core'
Traceback (most recent call last):
  File "/media/bin/pyload/stable/module/HookManager.py", line 88, in new
    return func(*args)
  File "/media/bin/pyload/stable/module/HookManager.py", line 198, in coreReady
    plugin.coreReady()
  File "/media/bin/pyload/stable/module/plugins/hooks/SJ.py", line 86, in coreReady
    self.core.api.setConfigValue("SerienjunkiesOrg", "changeNameSJ", "Packagename", section='plugin')
AttributeError: 'SJ' object has no attribute 'core'
```

Ist das ein pyload "Fehler" oder eine notwendige Anpassung an SJ.py ?

**Comment by Gutz-Pilz** [comment]
werden wir sehen.
Es wurden einige grundlegende Dinge bei pyLoad geändert.
Muss mir erst ein überblick verschaffen wie die Addon/Hook geschichte jetzt neuerdings gehandelt wird

**Comment by Gutz-Pilz** [comment]
fixed
https://github.com/Gutz-Pilz/pyLoad-stuff/commit/de4f193424b9c185e4dffeb44cb3017f3eea3fc0
