### ISSUE TITLE
HDAreaOrg: list index out of range

### ISSUE THREAD

**Issue by KelghAr** [Gutz-Pilz/pyLoad-stuff#52]
Hi,
Es gibt aktuell ein kleines Problem mit dem HDAreaOrg hook.

Die Fehlermeldung sieht ca so aus:

30.09.2015 18:14:05 ERROR     HOOK HDAreaOrg: Error executing periodical task: list index out of range
Traceback (most recent call last):
  File "/home/pyload/git/pyload/module/plugins/internal/Addon.py", line 99, in _periodical
    self.periodical()
  File "/home/pyload/.pyload/userplugins/hooks/HDAreaOrg.py", line 96, in periodical
    self.get_title(soup)
  File "/home/pyload/.pyload/userplugins/hooks/HDAreaOrg.py", line 119, in get_title
    self.get_download(all, title)
  File "/home/pyload/.pyload/userplugins/hooks/HDAreaOrg.py", line 131, in get_download
    self.get_year(soup1, title, url)
  File "/home/pyload/.pyload/userplugins/hooks/HDAreaOrg.py", line 139, in get_year
    imdb_url = re.findall(r'(https?:\/\/?imdb.com.+)', imdb_url)[0]
IndexError: list index out of range

Das Problem scheint zu sein, dass die imdb links manchmal ".com" und manchmal ".de" sind. Ich habe den oben stehenden regulären Ausdruck durch sowas ersetzt: "(https?:\/\/?imdb.(de|com).+)" 
Die Zeile sieht dann irgendwie so aus: 
imdb_url = re.findall(r'(https?:\/\/?imdb.(de|com).+)', imdb_url)[0][0]

**Comment by Gutz-Pilz** [comment]
okay. cool.
funktioniert es dann mit deiner änderung ?

**Comment by Gutz-Pilz** [comment]
hab die fehlermeldung nicht reproduzieren können.
deine änderung seht aber gut aus und die regex scheint zu funktionieren. 

hab es geändert.
DANKE!

**Comment by KelghAr** [comment]
Cool, war gerade dabei noch ne Antwort zu tippen.... :)

**Comment by KelghAr** [comment]
Ich hab mir gerade mal die Änderung angesehen und ich glaube du hast ein "[0]" am Ende vergessen :) So bekommt man nämlich die folgende Fehlermeldung:
  File "/home/pyload/git/pyload/module/plugins/internal/Addon.py", line 99, in _periodical
    self.periodical()
  File "/home/pyload/.pyload/userplugins/hooks/HDAreaOrg.py", line 96, in periodical
    self.get_title(soup)
  File "/home/pyload/.pyload/userplugins/hooks/HDAreaOrg.py", line 119, in get_title
    self.get_download(all, title)
  File "/home/pyload/.pyload/userplugins/hooks/HDAreaOrg.py", line 131, in get_download
    self.get_year(soup1, title, url)
  File "/home/pyload/.pyload/userplugins/hooks/HDAreaOrg.py", line 139, in get_year
    page = urllib2.urlopen(imdb_url).read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 422, in open
    req.timeout = timeout
AttributeError: 'tuple' object has no attribute 'timeout'

**Comment by Gutz-Pilz** [comment]
gesagt getan.
danke nochmals!
:+1:

**Comment by KelghAr** [comment]
Sieht gut aus! Danke dir!
