### ISSUE TITLE
SJ Fehler

### ISSUE THREAD

**Issue by b2un0** [Gutz-Pilz/pyLoad-stuff#59]
```
ERROR	HOOK SJ: Error executing periodical task: local variable 'storage' referenced before assignment

ERROR	Traceback (most recent call last):
619	?	?	File "/usr/bin/pyLoadCore", line 667, in
620	?	?	main()
621	?	?	File "/usr/bin/pyLoadCore", line 654, in main
622	?	?	deamon()
623	?	?	File "/usr/bin/pyLoadCore", line 646, in deamon
624	?	?	pyload_core.start()
625	?	?	File "/usr/bin/pyLoadCore", line 469, in start
626	?	?	self.scheduler.work()
627	?	?	File "/usr/share/pyload/module/Scheduler.py", line 85, in work
628	?	?	j.start()
629	?	?	File "/usr/share/pyload/module/Scheduler.py", line 111, in start
630	?	?	self.run()
631	?	?	File "/usr/share/pyload/module/Scheduler.py", line 101, in run
632	?	?	ret = self.call(*self.args, **self.kwargs)
633	?	?	File "/root/.pyload/userplugins/internal/Addon.py", line 118, in _periodical
634	?	?	self.periodical()
635	?	?	File "/root/.pyload/userplugins/hooks/SJ.py", line 158, in periodical
636	?	?	self.range_checkr(link,title)
637	?	?	File "/root/.pyload/userplugins/hooks/SJ.py", line 195, in range_checkr
638	?	?	self.parse_download(link, title)
639	?	?	File "/root/.pyload/userplugins/hooks/SJ.py", line 221, in parse_download
640	?	?	self.send_package(title,items) if len(items) > 0 else True
641	?	?	File "/root/.pyload/userplugins/hooks/SJ.py", line 228, in send_package
642	?	?	if storage == 'downloaded':
643	?	?	UnboundLocalError: local variable 'storage' referenced before assignment
```

**Comment by Gutz-Pilz** [comment]
ja. mach ein backup von files.db und lösche sie. 
danach ging es bei mir wieder

**Comment by b2un0** [comment]
Hat geholfen, danke :)
