### ISSUE TITLE
Error executing periodical task: local variable 'storage' referenced before assignment Traceback (most recent call last):

### ISSUE THREAD

**Issue by sveni-lee** [Gutz-Pilz/pyLoad-stuff#62]
I've done a update since a long time ago. Now I get the following error:

8.10.2015 21:17:56 ERROR     HOOK SJ: Error executing periodical task: local variable 'storage' referenced before assignment
Traceback (most recent call last):
  File "/usr/bin/pyLoadCore", line 667, in <module>
    main()
  File "/usr/bin/pyLoadCore", line 658, in main
    pyload_core.start()
  File "/usr/bin/pyLoadCore", line 469, in start
    self.scheduler.work()
  File "/usr/share/pyload/module/Scheduler.py", line 85, in work
    j.start()
  File "/usr/share/pyload/module/Scheduler.py", line 111, in start
    self.run()
  File "/usr/share/pyload/module/Scheduler.py", line 101, in run
    ret = self.call(*self.args, **self.kwargs)
  File "/home/svenilee/.pyload/userplugins/internal/Addon.py", line 121, in _periodical
    self.log_error(_("Error executing periodical task: %s") % e, trace=True)
18.10.2015 21:18:01 ERROR     HOOK HDAreaOrg: Error executing periodical task: Incorrect padding
Traceback (most recent call last):
  File "/usr/bin/pyLoadCore", line 667, in <module>
    main()
  File "/usr/bin/pyLoadCore", line 658, in main
    pyload_core.start()
  File "/usr/bin/pyLoadCore", line 469, in start
    self.scheduler.work()
  File "/usr/share/pyload/module/Scheduler.py", line 85, in work
    j.start()
  File "/usr/share/pyload/module/Scheduler.py", line 111, in start
    self.run()
  File "/usr/share/pyload/module/Scheduler.py", line 101, in run
    ret = self.call(*self.args, **self.kwargs)
  File "/home/svenilee/.pyload/userplugins/internal/Addon.py", line 121, in _periodical
    self.log_error(_("Error executing periodical task: %s") % e, trace=True)

**Comment by Gutz-Pilz** [comment]
Please use the latest version of my hooks and delete files.db


Johannes Müller

**Comment by sveni-lee** [comment]
Thanks, that solved the problem...
