### ISSUE TITLE
 ADDON HDAreaOrg: Error performing periodical task | 'HDAreaOrg' object has no attribute 'plugin'

### ISSUE THREAD

**Issue by sveni-lee** [Gutz-Pilz/pyLoad-stuff#80]
Ich habe jetzt den Plugin Ordner zweimal aktualisiert aber der Fehler taucht bei dem HDAreaOrg und SJ plugin auf...

was kann ich noch tun?

**Comment by Gutz-Pilz** [comment]
pyload updaten

**Comment by sveni-lee** [comment]
also ich habe den plugin im Verzeichnis /home/svenilee/.pyload/userplugins komplett erneuert....
muß ich den Plugin ordner unter /usr/share/pyload/module/ auch erneuern?

**Comment by sveni-lee** [comment]
ich habe es grad noch einmal versucht... alle plugins sind auf dem neusten Stand. Ich bekomme immernoch den selben fehler...

`30.01.2016 15:35:01 INFO      ADDON UpdateManager: All plugins are up to date!
30.01.2016 15:35:21 DEBUG     ADDON SJ: Abgelehnt: [DEUTSCH] Bob.der.Baumeister.S19E24.Der.goldene.Stern.GERMAN.WS.720p.HDTV.x264-aWake
30.01.2016 15:35:21 DEBUG     ADDON SJ: Abgelehnt: [DEUTSCH] Kuestenwache.S17E24.Das.Geheimnis.der.Turanga.WS.720p.HDTV.x264-pbw
30.01.2016 15:35:21 DEBUG     ADDON SJ: plugin.db.retrieve got exception, title: Scorpion.S02E02.Cuba.Libre.GERMAN.DUBBED.DL.720p.WebHD.x264-TVP
30.01.2016 15:35:21 ERROR     ADDON SJ: Error performing periodical task | local variable 'storage' referenced before assignment
Traceback (most recent call last):
  File "/usr/bin/pyLoadCore", line 667, in <module>
    main()
  File "/usr/bin/pyLoadCore", line 658, in main
    pyload_core.start()
  File "/usr/bin/pyLoadCore", line 469, in start
    self.scheduler.work()
  File "/usr/share/pyload/module/Scheduler.py", line 85, in work
    j.start()
  File "/usr/share/pyload/module/Scheduler.py", line 111, in start
    self.run()
  File "/usr/share/pyload/module/Scheduler.py", line 101, in run
    ret = self.call(*self.args, **self.kwargs)
  File "/home/svenilee/.pyload/userplugins/internal/misc.py", line 182, in _task
    self.task()
  File "/home/svenilee/.pyload/userplugins/hooks/SJ.py", line 162, in periodical_task
    self.range_checkr(link,title)
  File "/home/svenilee/.pyload/userplugins/hooks/SJ.py", line 199, in range_checkr
    self.parse_download(link, title)
  File "/home/svenilee/.pyload/userplugins/hooks/SJ.py", line 225, in parse_download
    self.send_package(title,items) if len(items) > 0 else True
  File "/home/svenilee/.pyload/userplugins/hooks/SJ.py", line 232, in send_package
    if storage == 'downloaded':
UnboundLocalError: local variable 'storage' referenced before assignment

30.01.2016 15:35:22 ERROR     ADDON HDAreaOrg: Error performing periodical task | 'HDAreaOrg' object has no attribute 'plugin'
Traceback (most recent call last):
  File "/usr/bin/pyLoadCore", line 667, in <module>
    main()
  File "/usr/bin/pyLoadCore", line 658, in main
    pyload_core.start()
  File "/usr/bin/pyLoadCore", line 469, in start
    self.scheduler.work()
  File "/usr/share/pyload/module/Scheduler.py", line 85, in work
    j.start()
  File "/usr/share/pyload/module/Scheduler.py", line 111, in start
    self.run()
  File "/usr/share/pyload/module/Scheduler.py", line 101, in run
    ret = self.call(*self.args, **self.kwargs)
  File "/home/svenilee/.pyload/userplugins/internal/misc.py", line 182, in _task
    self.task()
  File "/home/svenilee/.pyload/userplugins/hooks/HDAreaOrg.py", line 97, in periodical_task
    self.get_title(soup)
  File "/home/svenilee/.pyload/userplugins/hooks/HDAreaOrg.py", line 116, in get_title
    fetched = self.plugin.db.retrieve(title)
AttributeError: 'HDAreaOrg' object has no attribute 'plugin'

30.01.2016 15:35:22 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
`
