### ISSUE TITLE
TraktFetcher: No module named utils

### ISSUE THREAD

**Issue by Sidirius** [Gutz-Pilz/pyLoad-stuff#81]
Beim speichern vom Trakt Modul bekomme ich im Log folgende Meldung:

```
09.02.2016 14:56:19 DEBUG     Redirected import module.plugins.hooks.TraktFetcher -> userplugins.hooks.TraktFetcher
09.02.2016 14:56:19 ERROR     Error importing TraktFetcher: No module named utils
```

Das Plugin läuft auch nicht / sucht nicht / startet nicht periodisch.

Wenn du mehr details brauchst einfach melden. 

Ergänzung: Hatte Probleme mit dem Utils Modul vermutet und dieses auch via pip nachinstalliert, leider keine Veränderung.

**Comment by Sidirius** [comment]
So habe diesmal ohne Daemon gestartet und noch folgende Ergänzung für dich:

```
09.02.2016 15:03:42 DEBUG     Redirected import module.plugins.hooks.TraktFetcher -> userplugins.hooks.TraktFetcher
09.02.2016 15:03:42 ERROR     Error importing TraktFetcher: No module named utils
Traceback (most recent call last):
  File "/opt/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/pyload/module/plugins/PluginManager.py", line 320, in load_module
    module = __import__(newname, globals(), locals(), [plugin])
  File "/opt/.pyload/userplugins/hooks/TraktFetcher.py", line 5, in <module>
    from module.plugins.internal.utils import json
ImportError: No module named utils
```

**Comment by feuerwasser85** [comment]
Hatte diesbezüglich auch schon mal nachgefragt. GutzPilz meinte, er käme im April wieder dazu.
Das Utils Modul ist kein Python Modul sondern ein Pyload Modul. Es sollte in /pyload/module/plugins/internal sein, bei mir ist es da auch nicht. Hatte ein ähnliches Problem mit derPlugin.py, die ich einfach dem Verzeichnis hinzugefügt hatte. Wenn Du den SourceCode der Utils findest, bitte melden!

**Comment by Sidirius** [comment]
Hallo Feuerwasser,

habe mal ein wenig rumprobiert und man kann statt den utils auch einfach die simplejason as jason nutzen, damit umgehen wir die utils.py. Habe dann noch den ein oderen anderen Fix übernommen und hänge nun an einer anderen Stelle. Wenn du magst, kann ich dies gerne hier auf github verfügbar machen. Bräuchte aber jemanden der mitarbeiten / mir helfen kann, habe von python nicht viel ahnung, auch wenn ich als Fachinformatiker zumindest verstehe was im code passiert ;-)

lg
Sid

**Comment by Sidirius** [comment]
So habe nun bis an einen bestimmten punkt die fehler gefixt stecke nun aber an einem anderen punkt definitiv fest!

Ich bekomme mittlerweile die Liste an Titeln aus Trakt.

Nun stecke ich quasi in der Suche nach den Titeln. Hier bekomme ich folgende Fehlermeldung im Debug:

```
10.02.2016 19:26:34 DEBUG     ADDON TraktFetcher: Terminator Genisysis on List!
10.02.2016 19:26:34 DEBUG     ADDON TraktFetcher: Guardians of the Galaxyis on List!
10.02.2016 19:26:34 DEBUG     ADDON TraktFetcher: Big Hero 6is on List!
10.02.2016 19:26:34 DEBUG     ADDON TraktFetcher: The Green Mileis on List!
10.02.2016 19:26:34 DEBUG     ADDON TraktFetcher: Back to the Futureis on List!
10.02.2016 19:26:34 DEBUG     ADDON TraktFetcher: Star Trekis on List!
10.02.2016 19:26:34 DEBUG     ADDON TraktFetcher: Star Trek Into Darknessis on List!
10.02.2016 19:26:34 DEBUG     ADDON TraktFetcher: Back to the Future Part IIis on List!
10.02.2016 19:26:34 DEBUG     ADDON TraktFetcher: Back to the Future Part IIIis on List!
10.02.2016 19:26:34 DEBUG     ADDON TraktFetcher: The Hitchhikers Guide to the Galaxyis on List!
10.02.2016 19:26:34 DEBUG     ADDON TraktFetcher: LOAD URL https://api.themoviedb.org/3/search/movie?api_key=4e33dc1073b5ad87851d8a4f506dc096&query=Terminator%20Genisys&language=de | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
10.02.2016 19:26:36 DEBUG     ADDON TraktFetcher: Suche "Terminator Genisys" auf HDArea
10.02.2016 19:26:36 ERROR     ADDON TraktFetcher: Error performing periodical task | 'unicode' object has no attribute 'get_text'
Traceback (most recent call last):
  File "/opt/pyload/pyLoadCore.py", line 667, in <module>
    main()
  File "/opt/pyload/pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "/opt/pyload/pyLoadCore.py", line 469, in start
    self.scheduler.work()
  File "/opt/pyload/module/Scheduler.py", line 85, in work
    j.start()
  File "/opt/pyload/module/Scheduler.py", line 111, in start
    self.run()
  File "/opt/pyload/module/Scheduler.py", line 101, in run
    ret = self.call(*self.args, **self.kwargs)
  File "/opt/pyload/module/plugins/internal/misc.py", line 182, in _task
    self.task()
  File "/opt/.pyload/userplugins/hooks/TraktFetcher.py", line 104, in periodical_task
    self.search(trakttitles)
  File "/opt/.pyload/userplugins/hooks/TraktFetcher.py", line 140, in search
    req_page = href.get_text()
AttributeError: 'unicode' object has no attribute 'get_text'
```

Kann mir hier vielleicht wer weiterhelfen?

lg
Sid
