### ISSUE TITLE
Funktioniert nicht mehr

### ISSUE THREAD

**Issue by sixteeN11** [Gutz-Pilz/pyLoad-stuff#91]
Traceback (most recent call last):
  File "/usr/bin/pyLoadCore", line 667, in <module>
    main()
  File "/usr/bin/pyLoadCore", line 658, in main
    pyload_core.start()
  File "/usr/bin/pyLoadCore", line 392, in start
    self.pluginManager = PluginManager(self)
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 50, in __init__
    self.createIndex()
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 73, in createIndex
    self.plugins["hooks"] = self.hookPlugins = self.parse("hooks")
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 196, in parse
    temp = self.parse(folder, pattern, plugins)
  File "/usr/share/pyload/module/plugins/PluginManager.py", line 163, in parse
    config = literal_eval(config[0].strip().replace("\n", "").replace("\r", ""))
  File "/usr/share/pyload/module/lib/SafeEval.py", line 44, in const_eval
    c = test_expr(expr, _const_codes)
  File "/usr/share/pyload/module/lib/SafeEval.py", line 33, in test_expr
    raise ValueError, "%s is not a valid expression" % expr
ValueError: (<span class="pl-s"><span class="pl-pds">&quot;</span>activated<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>bool<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Activated<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>False<span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L14" class="blob-num js-line-number" data-line-number="14"></td>        <td id="LC14" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L15" class="blob-num js-line-number" data-line-number="15"></td>        <td id="LC15" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>destination<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>folder<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>destination folder<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span><span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L16" class="blob-num js-line-number" data-line-number="16"></td>        <td id="LC16" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L17" class="blob-num js-line-number" data-line-number="17"></td>        <td id="LC17" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>conflict<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;&quot;&quot;</span>skip;override<span class="pl-pds">&quot;&quot;&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>conflict handling<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>override<span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L18" class="blob-num js-line-number" data-line-number="18"></td>        <td id="LC18" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L19" class="blob-num js-line-number" data-line-number="19"></td>        <td id="LC19" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>action<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;&quot;&quot;</span>move;copy;test<span class="pl-pds">&quot;&quot;&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>copy, move or test(dry run)<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>move<span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L20" class="blob-num js-line-number" data-line-number="20"></td>        <td id="LC20" class="blob-code blob-code-inner js-file-line">                  </td>      </tr>      <tr>        <td id="L21" class="blob-num js-line-number" data-line-number="21"></td>        <td id="LC21" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>unsorted<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;&quot;&quot;</span>y;n<span class="pl-pds">&quot;&quot;&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>sort out files that cannot be proceed to $destination/unsorted/<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>n<span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L22" class="blob-num js-line-number" data-line-number="22"></td>        <td id="LC22" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L23" class="blob-num js-line-number" data-line-number="23"></td>        <td id="LC23" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>lang<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>str<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>language (en, de, fr, es, etc)<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>de<span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L24" class="blob-num js-line-number" data-line-number="24"></td>        <td id="LC24" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L25" class="blob-num js-line-number" data-line-number="25"></td>        <td id="LC25" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>subtitles<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>str<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>subtitles language (en, de, fr, es, etc)<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>de<span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L26" class="blob-num js-line-number" data-line-number="26"></td>        <td id="LC26" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L27" class="blob-num js-line-number" data-line-number="27"></td>        <td id="LC27" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>ignore<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>str<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>ignore files (regex)<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span><span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L28" class="blob-num js-line-number" data-line-number="28"></td>        <td id="LC28" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L29" class="blob-num js-line-number" data-line-number="29"></td>        <td id="LC29" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>artwork<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;&quot;&quot;</span>y;n<span class="pl-pds">&quot;&quot;&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>download artwork<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>y<span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L30" class="blob-num js-line-number" data-line-number="30"></td>        <td id="LC30" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L31" class="blob-num js-line-number" data-line-number="31"></td>        <td id="LC31" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>clean<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;&quot;&quot;</span>y;n<span class="pl-pds">&quot;&quot;&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>clean folder from clutter thats left behind<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>y<span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L32" class="blob-num js-line-number" data-line-number="32"></td>        <td id="LC32" class="blob-code blob-code-inner js-file-line">                  </td>      </tr>      <tr>        <td id="L33" class="blob-num js-line-number" data-line-number="33"></td>        <td id="LC33" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>storeReport<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;&quot;&quot;</span>y;n<span class="pl-pds">&quot;&quot;&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>save reports to local filesystem<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>n<span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L34" class="blob-num js-line-number" data-line-number="34"></td>        <td id="LC34" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L35" class="blob-num js-line-number" data-line-number="35"></td>        <td id="LC35" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>movie<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>str<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>movie destination (relative to destination or absolute)<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span><span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L36" class="blob-num js-line-number" data-line-number="36"></td>        <td id="LC36" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L37" class="blob-num js-line-number" data-line-number="37"></td>        <td id="LC37" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>series<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>str<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>series destination (relative to destination or absolute)<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span><span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L38" class="blob-num js-line-number" data-line-number="38"></td>        <td id="LC38" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L39" class="blob-num js-line-number" data-line-number="39"></td>        <td id="LC39" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>excludeList<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>str<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>exclude list file<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>pyload-amc.txt<span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L40" class="blob-num js-line-number" data-line-number="40"></td>        <td id="LC40" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L41" class="blob-num js-line-number" data-line-number="41"></td>        <td id="LC41" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>reperror<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;&quot;&quot;</span>y;n<span class="pl-pds">&quot;&quot;&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Report Error via Email<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>n<span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L42" class="blob-num js-line-number" data-line-number="42"></td>        <td id="LC42" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L43" class="blob-num js-line-number" data-line-number="43"></td>        <td id="LC43" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>filebot<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>str<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>filebot executable<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>filebot<span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L44" class="blob-num js-line-number" data-line-number="44"></td>        <td id="LC44" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L45" class="blob-num js-line-number" data-line-number="45"></td>        <td id="LC45" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>exec<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>str<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>additional exec script<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span><span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L46" class="blob-num js-line-number" data-line-number="46"></td>        <td id="LC46" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L47" class="blob-num js-line-number" data-line-number="47"></td>        <td id="LC47" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>no-xattr<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>bool<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>no-xattr<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>False<span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L48" class="blob-num js-line-number" data-line-number="48"></td>        <td id="LC48" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L49" class="blob-num js-line-number" data-line-number="49"></td>        <td id="LC49" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>xbmc<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>str<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>xbmc hostname<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span><span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L50" class="blob-num js-line-number" data-line-number="50"></td>        <td id="LC50" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L51" class="blob-num js-line-number" data-line-number="51"></td>        <td id="LC51" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>plex<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>str<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>plex hostname<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span><span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L52" class="blob-num js-line-number" data-line-number="52"></td>        <td id="LC52" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L53" class="blob-num js-line-number" data-line-number="53"></td>        <td id="LC53" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>plextoken<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>str<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>plex token (only needed with external plex servers)<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span><span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L54" class="blob-num js-line-number" data-line-number="54"></td>        <td id="LC54" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L55" class="blob-num js-line-number" data-line-number="55"></td>        <td id="LC55" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>extras<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;&quot;&quot;</span>y;n<span class="pl-pds">&quot;&quot;&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>create .url with all available backdrops<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>n<span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L56" class="blob-num js-line-number" data-line-number="56"></td>        <td id="LC56" class="blob-code blob-code-inner js-file-line">                  </td>      </tr>      <tr>        <td id="L57" class="blob-num js-line-number" data-line-number="57"></td>        <td id="LC57" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>pushover<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>str<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>pushover user-key<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span><span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L58" class="blob-num js-line-number" data-line-number="58"></td>        <td id="LC58" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L59" class="blob-num js-line-number" data-line-number="59"></td>        <td id="LC59" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>pushbullet<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>str<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>pushbullet api-key<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span><span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L60" class="blob-num js-line-number" data-line-number="60"></td>        <td id="LC60" class="blob-code blob-code-inner js-file-line"></td>      </tr>      <tr>        <td id="L61" class="blob-num js-line-number" data-line-number="61"></td>        <td id="LC61" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>cleanfolder<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>bool<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>remove DownloadFolder after moving<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>False<span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L62" class="blob-num js-line-number" data-line-number="62"></td>        <td id="LC62" class="blob-code blob-code-inner js-file-line">                  </td>      </tr>      <tr>        <td id="L63" class="blob-num js-line-number" data-line-number="63"></td>        <td id="LC63" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>output_to_log<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>bool<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>write FileBot Output to pyLoad Logfile<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>True<span class="pl-pds">&quot;</span></span>),</td>      </tr>      <tr>        <td id="L64" class="blob-num js-line-number" data-line-number="64"></td>        <td id="LC64" class="blob-code blob-code-inner js-file-line">                  </td>      </tr>      <tr>        <td id="L65" class="blob-num js-line-number" data-line-number="65"></td>        <td id="LC65" class="blob-code blob-code-inner js-file-line">                  (<span class="pl-s"><span class="pl-pds">&quot;</span>delete_extracted<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>bool<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>Delete archives after succesful extraction<span class="pl-pds">&quot;</span></span>, <span class="pl-s"><span class="pl-pds">&quot;</span>True<span class="pl-pds">&quot;</span></span>) is not a valid expression

**Comment by Gutz-Pilz** [comment]
leider biete ich keinen support mehr...
ich nutze mittlerweile jdownloader
